### ISSUE TITLE
ionic-plugin-keyboard is deprecated

### ISSUE THREAD

**Issue by kbullaughey** [isleofcode/ember-cordova-keyboard#9]
I noticed that [ionic-plugin-keyboard](https://github.com/ionic-team/ionic-plugin-keyboard) is deprecated. And the project indicates that [cordova-plugin-ionic-keyboard](https://github.com/ionic-team/cordova-plugin-ionic-keyboard) is the successor. Any idea if this can be swapped in?

**Comment by alexblom** [comment]
For our use that plugin is interchangeable. I'll aim to do a release later this week, please do PR sooner if you get the time.

**Comment by kbullaughey** [comment]
I've submitted a PR, issue #10, but see the discussion there, I'm not sure how to make the upgrade seamless for existing projects.

**Comment by alexblom** [comment]
Merged - sorry on taking so long
